name: My Action
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  pull_request_target:
    types: [opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked, review_requested, review_request_removed, labeled, unlabeled, assigned, unassigned, opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked, review_requested, review_request_removed, labeled, unlabeled, assigned, unassigned]
    branches: [main]
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir test
